WITH MAX_FISH_LEN AS (
    SELECT 
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH 
    FROM 
        FISH_INFO
    GROUP BY FISH_TYPE	
)
SELECT i.ID, n.FISH_NAME, m.MAX_LENGTH AS LENGTH
FROM MAX_FISH_LEN m 
JOIN FISH_NAME_INFO n
ON m.FISH_TYPE = n.FISH_TYPE
JOIN FISH_INFO i
ON m.MAX_LENGTH = i.LENGTH AND i.FISH_TYPE = m.FISH_TYPE
ORDER BY i.ID



/* 2
SELECT
    i.ID,
    n.FISH_NAME,
    i.LENGTH
FROM
    FISH_INFO i
INNER JOIN 
    FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE
INNER JOIN (
    SELECT
        ID,
        FISH_TYPE,
        ROW_NUMBER() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS rn
    FROM
        FISH_INFO
    WHERE LENGTH IS NOT NULL 
) AS RankedFish ON 
    i.ID = RankedFish.ID
WHERE
    RankedFish.rn = 1
ORDER BY 
    i.ID ASC;
*/