WITH VIEW_RANKING AS (
    SELECT BOARD_ID, RANK() OVER(ORDER BY VIEWS DESC) AS RANKING
    FROM USED_GOODS_BOARD
)

SELECT CONCAT("/home/grep/src/", f.BOARD_ID, "/", f.FILE_ID, f.FILE_NAME, f.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_FILE f
ON b.BOARD_ID = f.BOARD_ID
WHERE b.BOARD_ID = (
    SELECT BOARD_ID
    FROM VIEW_RANKING
    WHERE RANKING = 1
)
ORDER BY f.FILE_ID DESC