WITH EMP_TOTAL_SCORE AS (
    SELECT EMP_NO, SUM(SCORE) AS TOTAL_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)
, RANK_TABLE AS (
    SELECT EMP_NO, RANK() OVER(ORDER BY TOTAL_SCORE DESC) AS "RANK", TOTAL_SCORE
    FROM EMP_TOTAL_SCORE
)

SELECT r.TOTAL_SCORE AS SCORE, e.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM RANK_TABLE r
JOIN HR_EMPLOYEES e
ON r.EMP_NO = e.EMP_NO
WHERE r.RANK = 1