WITH SALES_DATA AS (
    SELECT b.AUTHOR_ID, b.CATEGORY, s.SALES, b.PRICE
    FROM BOOK_SALES s
    JOIN BOOK b
    ON s.BOOK_ID = b.BOOK_ID
    WHERE '2022-01-01' <= s.SALES_DATE AND s.SALES_DATE < '2022-02-01'
)

SELECT s.AUTHOR_ID, a.AUTHOR_NAME, s.CATEGORY, SUM(s.SALES * s.PRICE) AS TOTAL_SALES
FROM SALES_DATA s
JOIN AUTHOR a
ON s.AUTHOR_ID = a.AUTHOR_ID
GROUP BY s.AUTHOR_ID, a.AUTHOR_NAME, s.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC
