WITH target AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING TOTAL_SALES >= 700000
)

SELECT u.USER_ID, u.NICKNAME, t.TOTAL_SALES
FROM target t 
JOIN USED_GOODS_USER  u
ON t.WRITER_ID = u.USER_ID
ORDER BY t.TOTAL_SALES ASC