WITH AVG_SAL_BY_DEPT AS (
    SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)

SELECT a.DEPT_ID, d.DEPT_NAME_EN, a.AVG_SAL
FROM AVG_SAL_BY_DEPT a
JOIN HR_DEPARTMENT d
ON a.DEPT_ID = d.DEPT_ID
ORDER BY AVG_SAL DESC

