WITH TARGET AS (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
    FROM BOOK_SALES
    WHERE '2022-01-01' <= SALES_DATE AND SALES_DATE < '2022-02-01'
    GROUP BY BOOK_ID
)

SELECT b.CATEGORY, SUM(t.TOTAL_SALES) AS TOTAL_SALES
FROM TARGET t
JOIN BOOK b
ON t.BOOK_ID = b.BOOK_ID
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC