WITH result AS (
    SELECT COUNT(*) AS FISH_COUNT, FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT r.FISH_COUNT, f.FISH_NAME
FROM result r
LEFT JOIN FISH_NAME_INFO f
ON r.FISH_TYPE = f.FISH_TYPE
ORDER BY FISH_COUNT DESC