WITH MAX_PRICE_PRODUCT AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT m.CATEGORY, m.MAX_PRICE, f.PRODUCT_NAME
FROM MAX_PRICE_PRODUCT m
JOIN FOOD_PRODUCT f
ON m.MAX_PRICE = f.PRICE AND m.CATEGORY = f.CATEGORY
ORDER BY m.MAX_PRICE DESC
