WITH T AS (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR

    UNION ALL SELECT 0 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 1 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 2 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 3 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 4 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 5 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 6 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 7 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 8 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 9 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 10 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 11 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 12 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 13 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 14 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 15 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 16 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 17 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 18 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 19 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 20 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 21 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 22 AS HOUR, 0 AS COUNT
    UNION ALL SELECT 23 AS HOUR, 0 AS COUNT
)
SELECT t.HOUR, SUM(t.COUNT) AS COUNT
FROM T t
GROUP BY t.HOUR
ORDER BY t.HOUR ASC