SELECT DISTINCT j.ID, j.EMAIL, j.FIRST_NAME, j.LAST_NAME
FROM (
    SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME, s.NAME
    FROM DEVELOPERS d JOIN SKILLCODES s
    ON (s.CODE & d.SKILL_CODE) != 0
) AS j
WHERE j.NAME IN('Python', 'C#')
ORDER BY ID ASC