WITH RECURSIVE GEN AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, g.GENERATION + 1 AS GENERATION
    FROM GEN g
    JOIN ECOLI_DATA e
    ON g.ID = e.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION ASC

/* 2
WITH RECURSIVE GEN AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT e.ID, g.GENERATION + 1 AS GENERATION
    FROM GEN g
    JOIN ECOLI_DATA e
    ON g.ID = e.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA e
    WHERE e.PARENT_ID = GEN.ID
)
GROUP BY GENERATION
ORDER BY GENERATION ASC
*/