SELECT count(f.FISH_TYPE) AS FISH_COUNT
FROM FISH_INFO f JOIN FISH_NAME_INFO n
ON f.FISH_TYPE = n.FISH_TYPE
WHERE n.FISH_NAME = 'BASS' OR n.FISH_NAME = 'SNAPPER'


# 2
SELECT COUNT(I.ID) AS FISH_COUNT
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE N.FISH_NAME IN ('BASS', 'SNAPPER');