WITH 
    FIRST_GENERATION (ID) AS (
        SELECT ID 
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL
    ),
    SECOND_GENERATION (ID) AS (
        SELECT  c.ID  
        FROM ECOLI_DATA c      
        JOIN FIRST_GENERATION f 
        ON c.PARENT_ID = f.ID      
    )
SELECT a.ID
FROM ECOLI_DATA a
JOIN SECOND_GENERATION s
ON a.PARENT_ID = s.ID
ORDER BY a.ID ASC


# 2
SELECT
    A.ID -- 3세대 ID
FROM
    ECOLI_DATA A -- 3세대
INNER JOIN
    ECOLI_DATA S ON A.PARENT_ID = S.ID -- S는 2세대
INNER JOIN
    ECOLI_DATA F ON S.PARENT_ID = F.ID -- F는 1세대
WHERE
    F.PARENT_ID IS NULL -- 1세대의 부모는 NULL이어야 함
ORDER BY
    A.ID ASC;