WITH _2021_JOINED AS (
    SELECT USER_ID, COUNT(*) OVER() AS TOTAL
    FROM USER_INFO
    WHERE YEAR(JOINED) = "2021"
),
_2021_TOTAL_COUNT AS (
    SELECT COUNT(*) AS _2021_TOTAL
    FROM _2021_JOINED
)

SELECT 
    YEAR(o.SALES_DATE) AS YEAR,
    MONTH(o.SALES_DATE) AS MONTH,
    COUNT(DISTINCT o.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT o.USER_ID) / (SELECT _2021_TOTAL FROM _2021_TOTAL_COUNT)
        ,1) AS PUCHASED_RATIO
FROM _2021_JOINED j
JOIN ONLINE_SALE o
ON j.USER_ID = o.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC