WITH NON AS (
    SELECT ANIMAL_ID, SEX_UPON_INTAKE
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE 'Intact%'
)
SELECT n.ANIMAL_ID, o.ANIMAL_TYPE, o.NAME
FROM NON n JOIN ANIMAL_OUTS o
ON n.ANIMAL_ID = o.ANIMAL_ID
WHERE o.SEX_UPON_OUTCOME LIKE 'Spayed%' OR o.SEX_UPON_OUTCOME LIKE 'Neutered%'



/* 2
SELECT
    A.ANIMAL_ID,
    A.ANIMAL_TYPE,
    A.NAME
FROM
    ANIMAL_INS A
INNER JOIN
    ANIMAL_OUTS B
ON
    A.ANIMAL_ID = B.ANIMAL_ID
WHERE
    A.SEX_UPON_INTAKE LIKE 'Intact%'
    AND (
        B.SEX_UPON_OUTCOME LIKE 'Spayed%' OR
        B.SEX_UPON_OUTCOME LIKE 'Neutered%'
    )
ORDER BY
    A.ANIMAL_ID ASC;
*/