WITH AVAIL AS (
    SELECT o.ANIMAL_ID
    FROM ANIMAL_OUTS o JOIN ANIMAL_INS i
    ON o.ANIMAL_ID = i.ANIMAL_ID
)
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS o
WHERE o.ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM AVAIL)
ORDER BY o.ANIMAL_ID ASC



/* 2
SELECT o.ANIMAL_ID, o.NAME
FROM ANIMAL_OUTS o
LEFT JOIN ANIMAL_INS i
    ON o.ANIMAL_ID = i.ANIMAL_ID
WHERE i.ANIMAL_ID IS NULL
ORDER BY o.ANIMAL_ID ASC;
*/
