WITH UPGRADABLES AS (
    SELECT DISTINCT(PARENT_ITEM_ID) AS ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (
    SELECT ITEM_ID
    FROM UPGRADABLES
)
ORDER BY ITEM_ID DESC

/* 2
SELECT
    i.ITEM_ID,
    i.ITEM_NAME,
    i.RARITY
FROM
    ITEM_INFO i
LEFT JOIN 
    ITEM_TREE t ON i.ITEM_ID = t.PARENT_ITEM_ID
WHERE
    t.ITEM_ID IS NULL
ORDER BY
    i.ITEM_ID DESC;
*/