WITH MEMBER_REVIEW AS (
    SELECT 
        MEMBER_ID,
        COUNT(MEMBER_ID) AS TOTAL_REVIEW_COUNT,
        RANK() OVER (ORDER BY COUNT(MEMBER_ID) DESC) AS REVIEW_RANK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
) 
SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d')
FROM REST_REVIEW r JOIN MEMBER_REVIEW mr
ON r.MEMBER_ID = mr.MEMBER_ID
JOIN MEMBER_PROFILE m
ON mr.MEMBER_ID = m.MEMBER_ID
WHERE REVIEW_RANK = 1
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC


/* 2
WITH MEMBER_REVIEW AS (
    SELECT 
        MEMBER_ID,
        COUNT(MEMBER_ID) AS TOTAL_REVIEW_COUNT,
        RANK() OVER (ORDER BY COUNT(MEMBER_ID) DESC) AS REVIEW_RANK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
) 
SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE m JOIN MEMBER_REVIEW mr
ON m.MEMBER_ID = mr.MEMBER_ID
JOIN REST_REVIEW r
ON mr.MEMBER_ID = r.MEMBER_ID
WHERE REVIEW_RANK = 1
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC
*/

