SELECT f.PRODUCT_ID, f.PRODUCT_NAME, (f.PRICE * SUM(o.AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT f JOIN FOOD_ORDER o
ON f.PRODUCT_ID = o.PRODUCT_ID
WHERE '2022-05-01' <= o.PRODUCE_DATE AND o.PRODUCE_DATE < '2022-06-01'
GROUP BY f.PRODUCT_ID, f.PRODUCT_NAME, f.PRICE
ORDER BY TOTAL_SALES DESC, f.PRODUCT_ID ASC

