WITH TRUCK_RENT_HISTORY AS (
    SELECT 
        h.HISTORY_ID,
        h.CAR_ID,
        c.DAILY_FEE,
        DATEDIFF(h.END_DATE, h.START_DATE) + 1 AS RENT_DAYS,
        CASE
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 < 7 THEN "7일 미만"
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 BETWEEN 7 AND 29 THEN "7일 이상"
            WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 BETWEEN 30 AND 89 THEN "30일 이상"
            ELSE "90일 이상"
         END AS RENT_DAYS_STRING
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    JOIN CAR_RENTAL_COMPANY_CAR c
    ON h.CAR_ID = c.CAR_ID
    WHERE c.CAR_TYPE = "트럭"
) 

SELECT 
    h.HISTORY_ID,
    ROUND(h.DAILY_FEE  * (1 - p.DISCOUNT_RATE / 100) * h.RENT_DAYS, 0) AS FEE
FROM TRUCK_RENT_HISTORY h
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
ON h.RENT_DAYS_STRING = p.DURATION_TYPE
AND p.CAR_TYPE = "트럭"

UNION ALL

SELECT 
    HISTORY_ID,
    ROUND(DAILY_FEE * RENT_DAYS, 0) AS FEE
FROM TRUCK_RENT_HISTORY
WHERE RENT_DAYS_STRING = "7일 미만"

ORDER BY FEE DESC, HISTORY_ID DESC

