WITH BOARD_COUNT_BY_USER AS (
    SELECT WRITER_ID, COUNT(*) AS BOARD_COUNT
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING BOARD_COUNT >= 3
)

SELECT 
    u.USER_ID,
    u.NICKNAME,
    CONCAT(u.CITY, " ", u.STREET_ADDRESS1, " ", u.STREET_ADDRESS2) AS 전체주소,
    CONCAT(
    SUBSTR(u.TLNO, 1, 3),
    '-',
    SUBSTR(u.TLNO, 4, 4),
    '-',
    SUBSTR(u.TLNO, 8, 4)
    ) AS 전화번호
FROM USED_GOODS_USER u
JOIN BOARD_COUNT_BY_USER c
ON u.USER_ID = c.WRITER_ID
ORDER BY USER_ID DESC