WITH best AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE 
)
SELECT best.FOOD_TYPE, i.REST_ID, i.REST_NAME, best.FAVORITES
FROM best
JOIN REST_INFO i
ON best.FOOD_TYPE = i.FOOD_TYPE AND best.FAVORITES = i.FAVORITES
ORDER BY best.FOOD_TYPE DESC

