WITH car AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
),
pos AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' AND '2022-10-16' <= END_DATE
    GROUP BY CAR_ID
)

SELECT c.CAR_ID, 
       CASE
        WHEN p.CAR_ID IS NOT NULL THEN '대여중'
        ELSE '대여 가능'
       END AS AVAILABILITY
FROM car c
LEFT JOIN pos p
ON c.CAR_ID = p.CAR_ID

ORDER BY CAR_ID DESC

/* 2
WITH car AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
*/