SELECT DATE_FORMAT(f.SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
f.PRODUCT_ID,
NULL AS USER_ID,
f.SALES_AMOUNT AS SALES_AMOUNT
FROM OFFLINE_SALE  f
WHERE '2022-03-01' <= f.SALES_DATE AND f.SALES_DATE < '2022-04-01'

UNION

SELECT DATE_FORMAT(o.SALES_DATE, "%Y-%m-%d") AS SALES_DATE,
o.PRODUCT_ID,
o.USER_ID,
o.SALES_AMOUNT AS SALES_AMOUNT
FROM ONLINE_SALE o
WHERE '2022-03-01' <= o.SALES_DATE AND o.SALES_DATE < '2022-04-01'

ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC



/* 2
SELECT
    DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, -- 1. 최종 출력 시에만 포맷팅 적용
    PRODUCT_ID,
    USER_ID,
    SALES_AMOUNT
FROM
    (
        SELECT  
        FROM  
        WHERE ...
           
        UNION ALL -- 2. UNION ALL로 변경하여 중복 제거 오버헤드 제거

        SELECT
        FROM
        WHERE ...
    ) AS Combined_Sales
ORDER BY
    SALES_DATE ASC, -- 3. 포맷 변환 전인 원본 DATE/DATETIME 타입으로 정렬
    PRODUCT_ID ASC,
    USER_ID ASC;
*/